<script lang="ts">
	/**
	 * AreaModal - Create/Edit Area Modal
	 *
	 * Centered modal for:
	 * - Creating new areas
	 * - Editing existing areas
	 * - Managing name, context, color, and documents
	 *
	 * Note: General areas cannot be renamed or deleted
	 *
	 * Auto-color generation:
	 * - On create mode, auto-generates a distinct color based on existing area colors
	 * - Shows "Auto" badge on auto-selected color
	 * - Marks already-used colors with visual distinction
	 * - User can override by selecting any color
	 *
	 * Renamed from FocusAreaModal - see DESIGN-SPACES-AND-FOCUS-AREAS.md
	 */
	import { fly, fade } from 'svelte/transition';
	import type { Area, CreateAreaInput, UpdateAreaInput } from '$lib/types/areas';
	import { documentStore } from '$lib/stores/documents.svelte';
	import type { Document } from '$lib/types/documents';
	import { generateDistinctColor } from '$lib/utils/colorGeneration';

	interface Props {
		open: boolean;
		area?: Area | null; // Null = create mode, Area = edit mode
		spaceId: string;
		/** Colors already in use by other areas (for auto-generation and visual feedback) */
		existingColors?: string[];
		onClose: () => void;
		onCreate: (input: CreateAreaInput) => Promise<void>;
		onUpdate: (id: string, input: UpdateAreaInput) => Promise<void>;
		onDelete?: (id: string) => Promise<void>;
	}

	let {
		open,
		area = null,
		spaceId,
		existingColors = [],
		onClose,
		onCreate,
		onUpdate,
		onDelete
	}: Props = $props();

	// Form state
	let name = $state('');
	let context = $state('');
	let color = $state('');
	let contextDocumentIds = $state<string[]>([]);
	let isSubmitting = $state(false);
	let isUploading = $state(false);
	let error = $state<string | null>(null);
	let showDeleteConfirm = $state(false);
	let fileInputRef = $state<HTMLInputElement | null>(null);

	// Auto-color generation state
	let autoGeneratedColor = $state<string | null>(null);
	let userOverrodeColor = $state(false);

	// Get document details for linked documents
	let linkedDocuments = $derived.by(() => {
		const docs: Document[] = [];
		for (const docId of contextDocumentIds) {
			const doc = documentStore.getDocumentById(docId);
			if (doc) docs.push(doc);
		}
		return docs;
	});

	// Color options (these match STARTER_PALETTE in colorGeneration.ts)
	const colorOptions = [
		{ value: '#3b82f6', label: 'Blue' },
		{ value: '#8b5cf6', label: 'Purple' },
		{ value: '#10b981', label: 'Green' },
		{ value: '#f59e0b', label: 'Amber' },
		{ value: '#ef4444', label: 'Red' },
		{ value: '#ec4899', label: 'Pink' },
		{ value: '#06b6d4', label: 'Cyan' },
		{ value: '#84cc16', label: 'Lime' }
	];

	// Check if a color is already used by another area
	function isColorUsed(colorValue: string): boolean {
		return existingColors.some((c) => c.toLowerCase() === colorValue.toLowerCase());
	}

	// Check if this color is the auto-generated one (and not overridden by user)
	let isAutoSelectedColor = $derived(
		!userOverrodeColor && autoGeneratedColor !== null && color === autoGeneratedColor
	);

	// Derived state
	let isEditMode = $derived(area !== null);
	let isGeneral = $derived(area?.isGeneral ?? false);
	let modalTitle = $derived(
		isEditMode
			? isGeneral
				? 'Edit General Area'
				: 'Edit Area'
			: 'Create Area'
	);
	let submitLabel = $derived(isEditMode ? 'Save Changes' : 'Create');
	let canDelete = $derived(isEditMode && onDelete && !isGeneral);

	// Reset form when modal opens/closes or area changes
	$effect(() => {
		if (open) {
			// Load documents for this space
			documentStore.loadDocuments(spaceId);

			if (area) {
				// Edit mode - load existing area data
				name = area.name;
				context = area.context ?? '';
				color = area.color ?? '';
				contextDocumentIds = [...(area.contextDocumentIds ?? [])];
				// No auto-generation in edit mode
				autoGeneratedColor = null;
				userOverrodeColor = false;
			} else {
				// Create mode - reset form and auto-generate color
				name = '';
				context = '';
				contextDocumentIds = [];

				// Generate a distinct color based on existing area colors
				const generatedColor = generateDistinctColor(existingColors);
				autoGeneratedColor = generatedColor;
				color = generatedColor;
				userOverrodeColor = false;
			}
			error = null;
			showDeleteConfirm = false;
		}
	});

	// Handle user color selection
	function selectColor(selectedColor: string) {
		color = selectedColor;
		// Track that user manually selected a color (even if same as auto)
		if (autoGeneratedColor !== null && selectedColor !== autoGeneratedColor) {
			userOverrodeColor = true;
		}
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			if (showDeleteConfirm) {
				showDeleteConfirm = false;
			} else {
				onClose();
			}
		}
	}

	function handleBackdropClick(e: MouseEvent) {
		if (e.target === e.currentTarget) {
			onClose();
		}
	}

	async function handleSubmit() {
		// Validate (General areas keep their name)
		const trimmedName = name.trim();
		if (!trimmedName && !isGeneral) {
			error = 'Name is required';
			return;
		}

		isSubmitting = true;
		error = null;

		try {
			if (isEditMode && area) {
				const updates: UpdateAreaInput = {};

				// General areas cannot have their name changed
				if (!isGeneral && trimmedName !== area.name) {
					updates.name = trimmedName;
				}

				if (context !== (area.context ?? '')) updates.context = context || undefined;
				if (color !== (area.color ?? '')) updates.color = color || undefined;

				// Always include document IDs in update
				const originalDocIds = area.contextDocumentIds ?? [];
				if (JSON.stringify(contextDocumentIds) !== JSON.stringify(originalDocIds)) {
					updates.contextDocumentIds = contextDocumentIds.length > 0 ? contextDocumentIds : undefined;
				}

				await onUpdate(area.id, updates);
			} else {
				const input: CreateAreaInput = {
					spaceId,
					name: trimmedName,
					context: context || undefined,
					color: color || undefined,
					contextDocumentIds: contextDocumentIds.length > 0 ? contextDocumentIds : undefined
				};
				await onCreate(input);
			}
			onClose();
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to save area';
		} finally {
			isSubmitting = false;
		}
	}

	// Document handling
	async function handleFileSelect(event: Event) {
		const input = event.target as HTMLInputElement;
		const file = input.files?.[0];
		if (!file) return;

		isUploading = true;
		error = null;

		try {
			const doc = await documentStore.uploadDocument(file, spaceId);
			if (doc) {
				contextDocumentIds = [...contextDocumentIds, doc.id];
			} else {
				error = documentStore.error || 'Failed to upload document';
			}
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to upload document';
		} finally {
			isUploading = false;
			// Reset file input
			if (fileInputRef) fileInputRef.value = '';
		}
	}

	function removeDocument(docId: string) {
		contextDocumentIds = contextDocumentIds.filter((id) => id !== docId);
	}

	function formatFileSize(bytes: number | undefined): string {
		if (bytes === undefined || bytes === null || isNaN(bytes)) return '';
		if (bytes < 1024) return `${bytes} B`;
		if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
		return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
	}

	async function handleDelete() {
		if (!area || !onDelete || isGeneral) return;

		isSubmitting = true;
		error = null;

		try {
			await onDelete(area.id);
			onClose();
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to delete area';
		} finally {
			isSubmitting = false;
		}
	}
</script>

<svelte:window onkeydown={handleKeydown} />

{#if open}
	<!-- Backdrop -->
	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<!-- svelte-ignore a11y_click_events_have_key_events -->
	<div
		class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
		transition:fade={{ duration: 150 }}
		onclick={handleBackdropClick}
	>
		<!-- Modal -->
		<div
			class="modal-container"
			role="dialog"
			aria-modal="true"
			aria-labelledby="modal-title"
			transition:fly={{ y: 20, duration: 200 }}
		>
			<!-- Header -->
			<header class="modal-header">
				<h2 id="modal-title" class="modal-title">{modalTitle}</h2>
				<button type="button" onclick={onClose} class="close-button" aria-label="Close">
					<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M6 18L18 6M6 6l12 12"
						/>
					</svg>
				</button>
			</header>

			<!-- Content -->
			<div class="modal-content">
				{#if showDeleteConfirm}
					<!-- Delete confirmation -->
					<div class="delete-confirm">
						<p class="delete-message">
							Are you sure you want to delete <strong>"{area?.name}"</strong>?
						</p>
						<p class="delete-warning">Tasks linked to this area will be unlinked.</p>
						<div class="delete-actions">
							<button
								type="button"
								class="btn-secondary"
								onclick={() => (showDeleteConfirm = false)}
								disabled={isSubmitting}
							>
								Cancel
							</button>
							<button
								type="button"
								class="btn-danger"
								onclick={handleDelete}
								disabled={isSubmitting}
							>
								{isSubmitting ? 'Deleting...' : 'Delete'}
							</button>
						</div>
					</div>
				{:else}
					<!-- Form -->
					<form
						onsubmit={(e) => {
							e.preventDefault();
							handleSubmit();
						}}
					>
						{#if error}
							<div class="error-message">{error}</div>
						{/if}

						<!-- General area info -->
						{#if isGeneral}
							<div class="general-info">
								<svg class="info-icon" viewBox="0 0 20 20" fill="currentColor">
									<path
										fill-rule="evenodd"
										d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
										clip-rule="evenodd"
									/>
								</svg>
								<span
									>The General area is the default area for this space. You can add context but cannot
									rename or delete it.</span
								>
							</div>
						{/if}

						<!-- Name field -->
						<div class="field">
							<label for="name" class="field-label">Name</label>
							{#if isGeneral}
								<input
									id="name"
									type="text"
									class="field-input"
									value={name}
									disabled
									title="General area cannot be renamed"
								/>
							{:else}
								<!-- svelte-ignore a11y_autofocus -->
								<input
									id="name"
									type="text"
									class="field-input"
									placeholder="e.g., DevOps, Marketing, Research"
									bind:value={name}
									disabled={isSubmitting}
									autofocus
								/>
							{/if}
						</div>

						<!-- Context field -->
						<div class="field">
							<label for="context" class="field-label">
								Context
								<span class="field-hint">(optional)</span>
							</label>
							<textarea
								id="context"
								class="field-textarea"
								placeholder="Add background information that helps the AI understand this area..."
								bind:value={context}
								disabled={isSubmitting}
								rows="4"
							></textarea>
							<p class="field-description">
								This context will be included in AI conversations when this area is active.
							</p>
						</div>

						<!-- Documents field -->
						<div class="field">
							<span class="field-label">
								Reference Documents
								<span class="field-hint">(optional)</span>
							</span>

							<!-- Linked documents list -->
							{#if linkedDocuments.length > 0}
								<div class="documents-list">
									{#each linkedDocuments as doc (doc.id)}
										<div class="document-item">
											<div class="document-icon">
												<svg
													class="w-4 h-4"
													fill="none"
													stroke="currentColor"
													viewBox="0 0 24 24"
												>
													<path
														stroke-linecap="round"
														stroke-linejoin="round"
														stroke-width="2"
														d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
													/>
												</svg>
											</div>
											<div class="document-info">
												<span class="document-name">{doc.title || doc.filename}</span>
												<span class="document-meta">
													{#if doc.fileSize}{formatFileSize(doc.fileSize)}{/if}
													{#if doc.fileSize && doc.charCount} · {/if}
													{#if doc.charCount}{doc.charCount.toLocaleString()} chars{/if}
												</span>
											</div>
											<button
												type="button"
												class="document-remove"
												onclick={() => removeDocument(doc.id)}
												disabled={isSubmitting || isUploading}
												title="Remove document"
											>
												<svg
													class="w-4 h-4"
													fill="none"
													stroke="currentColor"
													viewBox="0 0 24 24"
												>
													<path
														stroke-linecap="round"
														stroke-linejoin="round"
														stroke-width="2"
														d="M6 18L18 6M6 6l12 12"
													/>
												</svg>
											</button>
										</div>
									{/each}
								</div>
							{/if}

							<!-- Upload button -->
							<div class="document-upload">
								<input
									bind:this={fileInputRef}
									type="file"
									id="document-upload"
									class="hidden"
									accept=".pdf,.doc,.docx,.txt,.md,.json,.csv"
									onchange={handleFileSelect}
									disabled={isSubmitting || isUploading}
								/>
								<label for="document-upload" class="upload-button" class:uploading={isUploading}>
									{#if isUploading}
										<svg class="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
											<circle
												class="opacity-25"
												cx="12"
												cy="12"
												r="10"
												stroke="currentColor"
												stroke-width="4"
											></circle>
											<path
												class="opacity-75"
												fill="currentColor"
												d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
											></path>
										</svg>
										<span>Uploading...</span>
									{:else}
										<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M12 4v16m8-8H4"
											/>
										</svg>
										<span>Add Document</span>
									{/if}
								</label>
							</div>
							<p class="field-description">
								PDF, Word, TXT, MD, JSON, CSV supported. Document content will be included in AI
								context.
							</p>
						</div>

						<!-- Color field (not for General) -->
						{#if !isGeneral}
							<div class="field">
								<label for="color" class="field-label">
									Color
									{#if isAutoSelectedColor}
										<span class="auto-badge">Auto</span>
									{/if}
								</label>
								<div class="color-options">
									{#each colorOptions as option (option.value)}
										{@const isUsed = isColorUsed(option.value)}
										{@const isSelected = color.toLowerCase() === option.value.toLowerCase()}
										{@const isAutoColor =
											autoGeneratedColor?.toLowerCase() === option.value.toLowerCase()}
										<button
											type="button"
											class="color-option"
											class:selected={isSelected}
											class:used={isUsed && !isSelected}
											class:auto={isAutoColor && isSelected && !userOverrodeColor}
											style="--option-color: {option.value}"
											onclick={() => selectColor(option.value)}
											disabled={isSubmitting}
											title={isUsed
												? `${option.label} (already used)`
												: isAutoColor && !userOverrodeColor
													? `${option.label} (auto-selected)`
													: option.label}
										>
											{#if isSelected}
												<svg class="check-icon" viewBox="0 0 20 20" fill="currentColor">
													<path
														fill-rule="evenodd"
														d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
														clip-rule="evenodd"
													/>
												</svg>
											{:else if isUsed}
												<!-- Show a subtle dot indicator for used colors -->
												<span class="used-indicator"></span>
											{/if}
										</button>
									{/each}
								</div>
								{#if !isEditMode}
									<p class="field-description">
										A color has been auto-selected for maximum distinction. Click any color to
										change.
									</p>
								{/if}
							</div>
						{/if}

						<!-- Actions -->
						<div class="modal-actions">
							{#if canDelete}
								<button
									type="button"
									class="btn-danger-outline"
									onclick={() => (showDeleteConfirm = true)}
									disabled={isSubmitting}
								>
									Delete
								</button>
							{/if}
							<div class="actions-right">
								<button
									type="button"
									class="btn-secondary"
									onclick={onClose}
									disabled={isSubmitting}
								>
									Cancel
								</button>
								<button
									type="submit"
									class="btn-primary"
									disabled={isSubmitting || (!name.trim() && !isGeneral)}
								>
									{isSubmitting ? 'Saving...' : submitLabel}
								</button>
							</div>
						</div>
					</form>
				{/if}
			</div>
		</div>
	</div>
{/if}

<style>
	.modal-container {
		width: 100%;
		max-width: 28rem;
		background: rgb(23, 23, 23);
		border: 1px solid rgba(255, 255, 255, 0.1);
		border-radius: 0.75rem;
		box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
		overflow: hidden;
	}

	.modal-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 1rem 1.5rem;
		border-bottom: 1px solid rgba(255, 255, 255, 0.1);
	}

	.modal-title {
		font-size: 1.125rem;
		font-weight: 600;
		color: #fff;
		margin: 0;
	}

	.close-button {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 2rem;
		height: 2rem;
		color: rgba(255, 255, 255, 0.5);
		border-radius: 0.375rem;
		transition: all 0.15s ease;
	}

	.close-button:hover {
		background: rgba(255, 255, 255, 0.1);
		color: #fff;
	}

	.modal-content {
		padding: 1.5rem;
	}

	.error-message {
		padding: 0.75rem 1rem;
		margin-bottom: 1rem;
		background: rgba(239, 68, 68, 0.1);
		border: 1px solid rgba(239, 68, 68, 0.3);
		border-radius: 0.5rem;
		color: #fca5a5;
		font-size: 0.875rem;
	}

	.general-info {
		display: flex;
		align-items: flex-start;
		gap: 0.625rem;
		padding: 0.75rem 1rem;
		margin-bottom: 1rem;
		background: rgba(59, 130, 246, 0.1);
		border: 1px solid rgba(59, 130, 246, 0.2);
		border-radius: 0.5rem;
		color: rgba(255, 255, 255, 0.8);
		font-size: 0.8125rem;
		line-height: 1.5;
	}

	.info-icon {
		width: 1rem;
		height: 1rem;
		color: #3b82f6;
		flex-shrink: 0;
		margin-top: 0.125rem;
	}

	.field {
		margin-bottom: 1.25rem;
	}

	.field-label {
		display: block;
		margin-bottom: 0.5rem;
		font-size: 0.875rem;
		font-weight: 500;
		color: rgba(255, 255, 255, 0.9);
	}

	.field-hint {
		font-weight: 400;
		color: rgba(255, 255, 255, 0.4);
	}

	.field-input,
	.field-textarea {
		width: 100%;
		padding: 0.625rem 0.875rem;
		background: rgba(255, 255, 255, 0.05);
		border: 1px solid rgba(255, 255, 255, 0.15);
		border-radius: 0.5rem;
		color: #fff;
		font-size: 0.9375rem;
		transition: all 0.15s ease;
	}

	.field-input:focus,
	.field-textarea:focus {
		outline: none;
		border-color: var(--space-accent, #3b82f6);
		box-shadow: 0 0 0 3px color-mix(in srgb, var(--space-accent, #3b82f6) 20%, transparent);
	}

	.field-input::placeholder,
	.field-textarea::placeholder {
		color: rgba(255, 255, 255, 0.3);
	}

	.field-input:disabled,
	.field-textarea:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.field-textarea {
		resize: vertical;
		min-height: 5rem;
	}

	.field-description {
		margin-top: 0.5rem;
		font-size: 0.8125rem;
		color: rgba(255, 255, 255, 0.4);
	}

	/* Document styles */
	.documents-list {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
		margin-bottom: 0.75rem;
	}

	.document-item {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		padding: 0.625rem 0.75rem;
		background: rgba(255, 255, 255, 0.05);
		border: 1px solid rgba(255, 255, 255, 0.1);
		border-radius: 0.5rem;
	}

	.document-icon {
		display: flex;
		align-items: center;
		justify-content: center;
		color: var(--space-accent, #3b82f6);
		flex-shrink: 0;
	}

	.document-info {
		flex: 1;
		min-width: 0;
		display: flex;
		flex-direction: column;
		gap: 0.125rem;
	}

	.document-name {
		font-size: 0.875rem;
		color: rgba(255, 255, 255, 0.9);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.document-meta {
		font-size: 0.75rem;
		color: rgba(255, 255, 255, 0.4);
	}

	.document-remove {
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 0.25rem;
		color: rgba(255, 255, 255, 0.4);
		border-radius: 0.25rem;
		transition: all 0.15s ease;
		flex-shrink: 0;
	}

	.document-remove:hover:not(:disabled) {
		background: rgba(239, 68, 68, 0.1);
		color: #ef4444;
	}

	.document-remove:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.document-upload {
		margin-bottom: 0.5rem;
	}

	.hidden {
		display: none;
	}

	.upload-button {
		display: inline-flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.5rem 0.875rem;
		font-size: 0.875rem;
		font-weight: 500;
		color: rgba(255, 255, 255, 0.7);
		background: rgba(255, 255, 255, 0.05);
		border: 1px dashed rgba(255, 255, 255, 0.2);
		border-radius: 0.5rem;
		cursor: pointer;
		transition: all 0.15s ease;
	}

	.upload-button:hover {
		background: rgba(255, 255, 255, 0.1);
		border-color: var(--space-accent, #3b82f6);
		color: rgba(255, 255, 255, 0.9);
	}

	.upload-button.uploading {
		opacity: 0.7;
		cursor: wait;
	}

	@keyframes spin {
		from {
			transform: rotate(0deg);
		}
		to {
			transform: rotate(360deg);
		}
	}

	.animate-spin {
		animation: spin 1s linear infinite;
	}

	.color-options {
		display: flex;
		gap: 0.5rem;
		flex-wrap: wrap;
	}

	.color-option {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 2rem;
		height: 2rem;
		background: var(--option-color);
		border: 2px solid transparent;
		border-radius: 0.375rem;
		cursor: pointer;
		transition: all 0.15s ease;
	}

	.color-option:hover:not(:disabled) {
		transform: scale(1.1);
	}

	.color-option.selected {
		border-color: #fff;
		box-shadow: 0 0 0 2px rgba(0, 0, 0, 0.3);
	}

	.color-option:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.check-icon {
		width: 1rem;
		height: 1rem;
		color: #fff;
	}

	/* Auto-generated color indicator badge */
	.auto-badge {
		display: inline-flex;
		align-items: center;
		padding: 0.125rem 0.375rem;
		margin-left: 0.5rem;
		font-size: 0.6875rem;
		font-weight: 500;
		text-transform: uppercase;
		letter-spacing: 0.025em;
		color: #10b981;
		background: rgba(16, 185, 129, 0.15);
		border: 1px solid rgba(16, 185, 129, 0.3);
		border-radius: 0.25rem;
	}

	/* Used color indicator (muted appearance) */
	.color-option.used {
		opacity: 0.4;
	}

	.color-option.used:hover:not(:disabled) {
		opacity: 0.7;
	}

	/* Used indicator dot */
	.used-indicator {
		width: 0.375rem;
		height: 0.375rem;
		background: rgba(255, 255, 255, 0.6);
		border-radius: 50%;
	}

	/* Auto-selected color glow effect */
	.color-option.auto {
		box-shadow: 0 0 0 2px rgba(16, 185, 129, 0.5);
	}

	.modal-actions {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-top: 1.5rem;
		padding-top: 1.5rem;
		border-top: 1px solid rgba(255, 255, 255, 0.1);
	}

	.actions-right {
		display: flex;
		gap: 0.75rem;
		margin-left: auto;
	}

	.btn-primary,
	.btn-secondary,
	.btn-danger,
	.btn-danger-outline {
		padding: 0.5rem 1rem;
		font-size: 0.875rem;
		font-weight: 500;
		border-radius: 0.375rem;
		transition: all 0.15s ease;
	}

	.btn-primary {
		background: var(--space-accent, #3b82f6);
		color: #fff;
	}

	.btn-primary:hover:not(:disabled) {
		background: color-mix(in srgb, var(--space-accent, #3b82f6) 80%, #fff);
	}

	.btn-primary:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.btn-secondary {
		background: rgba(255, 255, 255, 0.1);
		color: rgba(255, 255, 255, 0.8);
	}

	.btn-secondary:hover:not(:disabled) {
		background: rgba(255, 255, 255, 0.15);
		color: #fff;
	}

	.btn-secondary:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.btn-danger {
		background: #ef4444;
		color: #fff;
	}

	.btn-danger:hover:not(:disabled) {
		background: #dc2626;
	}

	.btn-danger:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.btn-danger-outline {
		background: transparent;
		color: #ef4444;
		border: 1px solid rgba(239, 68, 68, 0.3);
	}

	.btn-danger-outline:hover:not(:disabled) {
		background: rgba(239, 68, 68, 0.1);
		border-color: rgba(239, 68, 68, 0.5);
	}

	.btn-danger-outline:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	/* Delete confirmation */
	.delete-confirm {
		text-align: center;
		padding: 1rem 0;
	}

	.delete-message {
		font-size: 1rem;
		color: #fff;
		margin-bottom: 0.5rem;
	}

	.delete-warning {
		font-size: 0.875rem;
		color: rgba(255, 255, 255, 0.5);
		margin-bottom: 1.5rem;
	}

	.delete-actions {
		display: flex;
		justify-content: center;
		gap: 0.75rem;
	}
</style>
