#!/bin/bash
################################################################################
# Create Deployment Package for AlmaLinux
# This script packages all necessary files for easy deployment
################################################################################

set -e

PACKAGE_NAME="librechat-deployment-$(date +%Y%m%d-%H%M%S)"
PACKAGE_DIR="./$PACKAGE_NAME"

echo "Creating deployment package: $PACKAGE_NAME"

# Create package directory
mkdir -p "$PACKAGE_DIR"

# Copy essential files
echo "Copying configuration files..."
cp docker-compose.yml "$PACKAGE_DIR/"
cp librechat.yaml "$PACKAGE_DIR/"
cp litellm-config.yaml "$PACKAGE_DIR/"
cp nginx-inject.conf "$PACKAGE_DIR/"
cp export-enhancer.js "$PACKAGE_DIR/"
cp export-api-v2.py "$PACKAGE_DIR/"
cp convert-export.sh "$PACKAGE_DIR/"
cp paste-and-convert.sh "$PACKAGE_DIR/"
cp download-server.py "$PACKAGE_DIR/" 2>/dev/null || true

# Copy installation script
cp install-almalinux.sh "$PACKAGE_DIR/"

# Copy documentation
cp CLAUDE.md "$PACKAGE_DIR/" 2>/dev/null || true
cp EXPORT-SETUP.md "$PACKAGE_DIR/" 2>/dev/null || true
cp exports/README-EXPORT-GUIDE.md "$PACKAGE_DIR/" 2>/dev/null || true

# Create README for the package
cat > "$PACKAGE_DIR/README.md" << 'EOF'
# LibreChat Deployment Package

This package contains everything needed to deploy LibreChat with LiteLLM and export functionality on AlmaLinux.

## Quick Start

1. **Copy this entire folder to your AlmaLinux server:**
   ```bash
   scp -r librechat-deployment-* user@your-server:/tmp/
   ```

2. **SSH into your server:**
   ```bash
   ssh user@your-server
   ```

3. **Run the installation script:**
   ```bash
   cd /tmp/librechat-deployment-*
   sudo bash install-almalinux.sh
   ```

4. **Access LibreChat:**
   - LibreChat: http://your-server-ip:3001
   - Login: admin@librechat.local / admin123

## What's Included

- **LibreChat** - Modern AI chat interface
- **LiteLLM** - Multi-model LLM proxy
- **MongoDB** - LibreChat database
- **PostgreSQL** - LiteLLM database
- **Gotenberg** - PDF conversion service
- **Export API** - PDF/DOCX export functionality
- **Nginx Proxy** - Auto-injects export buttons

## Features

✅ Auto-injected PDF/DOCX export buttons (no extensions needed)
✅ Multi-LLM support via LiteLLM
✅ Complete Docker setup
✅ Automatic service configuration
✅ Firewall configuration
✅ All prerequisites installed

## System Requirements

- **OS:** AlmaLinux 8/9 (or compatible RHEL-based)
- **RAM:** 4GB minimum, 8GB recommended
- **Disk:** 20GB free space
- **Ports:** 3001, 4000, 8080, 8081

## Post-Installation

After installation completes:

1. **Add Your API Keys:**
   - Go to http://your-server-ip:4000 (LiteLLM UI)
   - Login with admin / sk-1234
   - Add your Anthropic, OpenAI, or other API keys

2. **Use Export Features:**
   - Open LibreChat (port 3001)
   - Look for export buttons in bottom-right corner
   - Click to download conversations as PDF or DOCX

3. **Manage Services:**
   ```bash
   cd /opt/librechat
   docker compose ps              # Status
   docker compose logs -f         # View logs
   docker compose restart         # Restart
   docker compose down            # Stop
   docker compose up -d           # Start
   ```

## Configuration Files

- `/opt/librechat/.env` - Environment variables
- `/opt/librechat/docker-compose.yml` - Service definitions
- `/opt/librechat/librechat.yaml` - LibreChat config
- `/opt/librechat/litellm-config.yaml` - LiteLLM config

## Support

For issues or questions, check:
- Installation log: `/var/log/librechat-install.log`
- Service logs: `docker compose logs`
- CLAUDE.md for architecture details
- EXPORT-SETUP.md for export feature details

## Security Notes

- Change default passwords after installation!
- Add SSL/TLS for production use
- Configure firewall rules as needed
- Keep API keys secure

## License

This deployment includes open-source components.
Check individual project licenses for details.
EOF

# Create exports directory
mkdir -p "$PACKAGE_DIR/exports"
mkdir -p "$PACKAGE_DIR/init-scripts"

# Create PostgreSQL init script
cat > "$PACKAGE_DIR/init-scripts/01-create-litellm-db.sql" << 'EOF'
-- Create LiteLLM database
CREATE DATABASE litellm_db;

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE litellm_db TO anythingllm;
EOF

# Create .env template
cat > "$PACKAGE_DIR/.env.template" << 'EOF'
# LibreChat Environment Configuration
# Copy this file to .env and fill in your values

# Security (auto-generated by install script)
JWT_SECRET=
AUTH_TOKEN=

# LLM Provider Configuration - ADD YOUR API KEYS HERE
# Uncomment and add your keys:
# ANTHROPIC_API_KEY=sk-ant-api03-your-key-here
# OPENAI_API_KEY=sk-your-openai-key-here

# LiteLLM Configuration
LLM_PROVIDER=openai
OPENAI_API_KEY=
OPENAI_BASE_URL=http://litellm:4000

# Embedding Configuration
EMBEDDING_ENGINE=openai
EMBEDDING_MODEL_PREF=text-embedding-3-small

# Vector Database
VECTOR_DB=lancedb

# LiteLLM Proxy
LITELLM_MASTER_KEY=sk-1234
UI_USERNAME=admin
UI_PASSWORD=sk-1234
STORE_MODEL_IN_DB=True

# Database
POSTGRES_PASSWORD=securepassword123

# Feature Flags
DISABLE_TELEMETRY=true

# Registration
ALLOW_REGISTRATION=true
ALLOW_UNVERIFIED_EMAIL_LOGIN=true
EOF

# Make scripts executable
chmod +x "$PACKAGE_DIR"/*.sh
chmod +x "$PACKAGE_DIR"/*.py 2>/dev/null || true

# Create tarball
echo "Creating tarball..."
tar czf "${PACKAGE_NAME}.tar.gz" "$PACKAGE_DIR"

# Cleanup
rm -rf "$PACKAGE_DIR"

echo
echo "✅ Deployment package created: ${PACKAGE_NAME}.tar.gz"
echo
echo "To deploy on AlmaLinux:"
echo "  1. scp ${PACKAGE_NAME}.tar.gz user@server:/tmp/"
echo "  2. ssh user@server"
echo "  3. cd /tmp && tar xzf ${PACKAGE_NAME}.tar.gz"
echo "  4. cd ${PACKAGE_NAME}"
echo "  5. sudo bash install-almalinux.sh"
echo
